CREATE TABLE IF NOT EXISTS change_review (
    id BIGINT NOT NULL AUTO_INCREMENT,
    operation VARCHAR(16) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_record_type VARCHAR(16) NOT NULL,
    source_record_id BIGINT NULL,
    function_code VARCHAR(16) NOT NULL,
    unique_key VARCHAR(255) NOT NULL,
    review_key VARCHAR(512) NOT NULL,
    policy_no VARCHAR(10) NULL,
    policy_seq INT NULL,
    change_case_no VARCHAR(20) NULL,
    content_before LONGTEXT NULL,
    content_after LONGTEXT NULL,
    review_status VARCHAR(1) NOT NULL DEFAULT 'P',
    created_by VARCHAR(128) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(128) NULL,
    updated_at DATETIME NULL,
    reviewed_by VARCHAR(128) NULL,
    reviewed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_change_review_key (review_key),
    KEY idx_change_review_query (function_code, review_status, policy_no, policy_seq),
    KEY idx_change_review_source (source_type, source_record_type, source_record_id, review_status),
    CONSTRAINT chk_change_review_operation CHECK (operation IN ('CREATE', 'UPDATE', 'DELETE')),
    CONSTRAINT chk_change_review_status CHECK (review_status IN ('P', 'S', 'C'))
);
